name: Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit ruff mypy
      - name: Install Trivy
        uses: aquasecurity/trivy-action@v2
        with:
          version: '0.43.3'
      - name: Run bandit
        run: bandit -r . || true
      - name: Run ruff
        run: ruff check . || true
      - name: Run mypy
        run: mypy . || true
      - name: Run Trivy filesystem scan
        id: trivy-filesystem
        uses: aquasecurity/trivy-action@v2
        with:
          scan-type: 'fs'
          format: 'json'
          output: 'reports/trivy_fs_report.json'
          severity: 'CRITICAL,HIGH'
      - name: Run Trivy image scan (if Dockerfile present)
        if: files.exists('Dockerfile') || github.event_name == 'push'
        run: |
          docker pull alpine:3.18 || true
          trivy image --format json -o reports/trivy_image_report.json --severity CRITICAL,HIGH --exit-code 0 $(basename $(pwd)) || true
      - name: TruffleHog secret scan
        uses: trufflesecurity/trufflehog-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_file: reports/trufflehog_report.json
          format: json
      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            reports/**

